In [1]:
import numpy as np

# task -1

In [3]:
arr1=np.arange(10,51)
print("1-D array: ",arr1)

1-D array:  [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [7]:
arr2=np.random.rand(3,3)
print("random 3x3 array: ",arr2)

random 3x3 array:  [[0.78717022 0.55898961 0.79182523]
 [0.6321225  0.76086958 0.83812107]
 [0.66627456 0.64288383 0.30368517]]


# task - 2 Array attributes

In [9]:
print("Shape of 3x3 Array:", arr2.shape)
print("Size of 3x3 Array:", arr2.size)
print("Data type of 3x3 Array:", arr2.dtype)

Shape of 3x3 Array: (3, 3)
Size of 3x3 Array: 9
Data type of 3x3 Array: float64


# task -3

In [43]:
arr3 = arr1 + 5
print("1D Array + 5:", arr3)

1D Array + 5: [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]


In [15]:
#Multiply two 2D arrays element-wise
a=np.array([[1, 2], [3, 4]])
b=np.array([[5, 6], [7, 8]])
product=a*b
print("Element wise Product:\n",product)

Element wise Product:
 [[ 5 12]
 [21 32]]


# task-4

In [45]:
arr4=np.arange(1, 26).reshape(5, 5)
print("5x5 Array: ", arr4)

5x5 Array:  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [19]:
first_row=arr4[0, :]
print("First Row:", first_row)

First Row: [1 2 3 4 5]


In [23]:
last_column=arr4[:, -1]
print("Last Column:",last_column)

Last Column: [ 5 10 15 20 25]


In [25]:
subarray=arr4[:3, :2]
print("Subarray:",subarray)

Subarray: [[ 1  2]
 [ 6  7]
 [11 12]]


# task-5

In [27]:
random_array=np.random.randint(1, 101,size=10)
print("Random Array:",random_array)

Random Array: [ 2 26 51 49 97 45 72  8 14 99]


In [29]:
print("Max Value:",random_array.max())
print("Min Value:",random_array.min())
print("Mean:",random_array.mean())
print("Standard Deviation:",random_array.std())

Max Value: 99
Min Value: 2
Mean: 46.3
Standard Deviation: 33.05162628373981


# task-6

In [31]:
array_reshaped=np.arange(1, 13).reshape(3, 4)
print("3x4 Matrix:",array_reshaped)

3x4 Matrix: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


# task-7

In [33]:
ones=np.ones((3, 3))
array_to_add=np.array([1, 2, 3])
result=ones+array_to_add
print("Broadcast Result:",result)

Broadcast Result: [[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


# task-8

In [35]:
random_integers=np.random.randint(1, 51,size=15)
print("Random Integers:",random_integers)

Random Integers: [50 27 31 42 48 36 30  2 21 20  4 25 39 37 50]


In [37]:
div_5 =random_integers[random_integers%5==0]
print("Divisible by 5:", div_5)

Divisible by 5: [50 30 20 25 50]


# task-9

In [39]:
matrix_1 =np.array([[1, 2],[3, 4]])
matrix_2 =np.array([[5, 6],[7, 8]])
matrix_product =np.dot(matrix_1, matrix_2)
print("Matrix Multiplication:\n",matrix_product)

Matrix Multiplication:
 [[19 22]
 [43 50]]


# task-10

In [41]:
arr5 =np.arange(1, 17).reshape(4, 4)
print("4x4 Array:\n", arr5)
diag_ele =arr5[np.arange(4), np.arange(4)]
print("Diagonal Elements:", diag_ele)

4x4 Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Diagonal Elements: [ 1  6 11 16]
